### ISSUE TITLE
Search Navigation not working

### ISSUE THREAD

**Issue by grajan777** [grlicaa/SearchNavigationMenu#1]
Sir,

I have downloaded your latest (11-08-2017) SearchNavigationMenu from GitHub. As instructed, I have imported SearchNavigationMenu, added a region onto global page and dragged SearchNavigationMenu plug-in item to the same region. When the application is run, the search item box is displayed above the menu but unfortunately it will not do any searching for any menu item entered in the search box.

I have the following suggestion in this regard. As your demo is working perfectly OK you could make this demo application available for download. This will enable the user to debug most of the issues himself  without disturbing you. 

George

**Comment by grlicaa** [comment]
Hy thanks for comment. Can you please give me some more specific APEX version, Browser version. 
I added application sample download https://apex.oracle.com/pls/apex/f?p=111583:15
