### ISSUE TITLE
Issues in APEX 5.1.3

### ISSUE THREAD

**Issue by hassanyameen** [grlicaa/SearchNavigationMenu#2]
Your plugin is really useful but its not working on APEX 5.1.3, although its working perfectly on 5.1.2 and older.

**Comment by grlicaa** [comment]
https://apex.oracle.com/pls/apex/f?p=111583   <--- 5.1.3. 
Working perfectly in every 5.x version for now even 5.1.3,....  can you be more specific what is issue ? 
Which part of SearchNavigationMenu is not working?
