### ISSUE TITLE
Internet Explorer 11

### ISSUE THREAD

**Issue by ericyuri** [grlicaa/SearchNavigationMenu#4]
I don't know if it's me, but can you try to execute and test the page on IE ?  It's not working for me. Thank you

**Comment by ScottishRoss** [comment]
Can you clarify what specifically isn't working? It works fine for me on IE11.

**Comment by ericyuri** [comment]
Hi Ross, I just tried again but it's not working on IE, as you can see, the IR doesn't show up with all the managers.
![2018-11-02_7-52-39](https://user-images.githubusercontent.com/13050062/47914070-a2944a00-de74-11e8-80ca-8ec55a1735fb.png)

**Comment by ScottishRoss** [comment]
Just tested it myself, I can confirm that this doesn't happen on IE11.

**Comment by grlicaa** [comment]
@ericyuri don't use IE11 !! :) no no just a joke.... 
I'll take a look at this problem for next version, if you solve problem by yourself please let me know !
Tnx, Best regards, Andrej

**Comment by ericyuri** [comment]
Hi Adrej, I don't use IE11, but I need to test in all browsers before sent the application to the user. Thank you and have a great weekend :)

**Comment by grlicaa** [comment]
Found the bug, and solved...
I needed to change .startsWidth(string) to... indexOf(string) == 0 because of IE
![image](https://user-images.githubusercontent.com/30799807/51785447-29954d80-2158-11e9-8f2f-19614b31424e.png)
