### ISSUE TITLE
Parent / Child Issues

### ISSUE THREAD

**Issue by ScottishRoss** [grlicaa/SearchNavigationMenu#7]
It seems that when searching for an item with a child item if you toggle the parent open/closed and then remove a character from the search, the whole search breaks and you have to refresh the page to fix it. Specifically when searching child items will no longer show.

Edit: I've been able to replicate this on Windows 10 now.

**Comment by grlicaa** [comment]
Version of APEX ?

**Comment by ScottishRoss** [comment]
APEX 5.0.4.

I have been able to replicate it on 5.1 / 18.1 as well.

I hope you understand the issue because I'm finding it hard to explain. 
I can search normally, and if there are child items it all shows fine.
![bug 1](https://user-images.githubusercontent.com/25175556/49573150-386c3a80-f935-11e8-9d2b-36818b802dc0.PNG)

But if I toggle the parent menu closed/open a few times, then remove a character from the search string it no longer shows the child items.

![bug 2](https://user-images.githubusercontent.com/25175556/49573151-3904d100-f935-11e8-825c-470af4ff12b5.PNG)

Even when re-adding the character to the search it's still broken. Researching/refreshing the page fixes restores it back to a working state.

![bug 3](https://user-images.githubusercontent.com/25175556/49573152-3904d100-f935-11e8-86f6-6d6bd0f3050a.PNG)

**Comment by grlicaa** [comment]
Fixed in release 2.1
